-- PARKED-006 — codex-driven-bug-hunt cycle 4 (MED, foundation compliance gap).
-- dedupeKey: job-billing-bridge:unpost_invoice:orphan_rup_sales_records
--
-- THE GAP
-- post_invoice → generate_rup_sales_records (live verified 2026-06-30) writes
-- ONE rup_sales_records row per (invoice_id, product_id) for every RUP product
-- on the invoice. The new unpost_invoice (20260625130000) deliberately leaves
-- those rows behind, citing "RUP sales records are an append-only legal/
-- compliance trail (a restricted-use-pesticide sale DID happen at post time);
-- unposting the bill does not unsell the chemical, so we intentionally leave
-- them." (lines 59-61 of the migration).
--
-- That framing is correct when the post was VALID and unpost is a workflow
-- pause — the legal record should persist. But unpost is ALSO documented as
-- the cure for an ACCIDENTAL post ("undo an accidental/early posting on a
-- still-unpaid bill", line 31). The RUP row generated by the accidental post
-- now records a sale that the office is explicitly removing from posted state.
-- A subsequent edit + re-post creates this state:
--   * The dedup in generate_rup_sales_records (`NOT EXISTS … same invoice_id +
--     product_id`) SKIPS the now-stale RUP row.
--   * If the products on the invoice CHANGED between the unpost and the re-
--     post (e.g., a wrong product was removed), the original stale row
--     persists, AND the corrected products get fresh RUP rows.
-- The compliance report (`get_rup_sales_register`, live-verified 2026-06-30 —
-- selects from rup_sales_records with no invoice-status filter) would then
-- show BOTH rows — the corrected sale AND the stale erroneous one — to any
-- auditor or regulator running it.
--
-- WHY MED, NOT HIGH
-- Live state today: 0 rup_sales_records (operationally empty; no compliance
-- corruption possible). HIGH parallels (PARKED-001, PARKED-003) touched the
-- money ledger directly; this touches a regulated audit trail with zero current
-- data. Upgrade to HIGH the moment the first RUP product is sold live.
--
-- THE FIX — append-only with a "voided" marker (regulatory-faithful pattern)
-- "Append-only" doesn't mean "rows must never be hidden from reports"; it
-- means "rows must never be silently deleted". The right pattern is a
-- void_at timestamp + a void reason, and a register report that filters
-- voided rows by default.
--
-- This migration does THREE things:
--   1. ADD 3 columns to rup_sales_records: voided_at timestamptz, voided_by
--      uuid, void_reason text. Nullable; existing rows keep voided_at = NULL.
--   2. Patch unpost_invoice to mark its invoice's RUP rows voided_at = now()
--      with reason 'Invoice unposted' (only the ones with voided_at IS NULL —
--      idempotent). The append-only ledger gains an 'rup_sales_voided' audit
--      row (additive CHECK superset, mirrors invoice_unposted).
--   3. Patch get_rup_sales_register to add `p_include_voided boolean DEFAULT
--      false` and filter voided_at IS NULL when not included. Existing callers
--      (no extra arg) get the current "active sales only" semantics — what
--      they almost certainly already expect.
--   4. (BONUS) Patch generate_rup_sales_records's dedup so a re-post can
--      regenerate a fresh active row even when a stale voided row exists for
--      the same (invoice_id, product_id) — change the NOT EXISTS predicate
--      from "same invoice_id AND product_id" to ALSO require voided_at IS NULL.
--      Without this, a re-post would dedup against the voided row and skip
--      legitimate new sales.
--
-- Every other byte of unpost_invoice / generate_rup_sales_records / get_rup_sales_register
-- is preserved verbatim. Reversible: drop the 3 columns, revert the 3 RPCs.
--
-- PARKED: do NOT apply without Mason's explicit OK.
-- ============================================================================

-- ── 1. Schema: add the void columns to rup_sales_records ─────────────────────
ALTER TABLE public.rup_sales_records
  ADD COLUMN IF NOT EXISTS voided_at  timestamptz NULL,
  ADD COLUMN IF NOT EXISTS voided_by  uuid        NULL REFERENCES public.profiles(id),
  ADD COLUMN IF NOT EXISTS void_reason text       NULL;

-- Helpful filter index (register reads + future-proof: dedup probe is no longer
-- selective enough without it as data accumulates).
CREATE INDEX IF NOT EXISTS idx_rup_sales_records_active
  ON public.rup_sales_records (invoice_id, product_id)
  WHERE voided_at IS NULL;

-- ── 2. Additive CHECK superset: add 'rup_sales_voided' to financial_audit_log ─
DO $$
DECLARE v_def text;
BEGIN
  SELECT pg_get_constraintdef(oid) INTO v_def
    FROM pg_constraint
   WHERE conrelid = 'public.financial_audit_log'::regclass
     AND conname  = 'financial_audit_log_operation_type_check';
  IF v_def IS NOT NULL AND position('rup_sales_voided' in v_def) = 0 THEN
    ALTER TABLE public.financial_audit_log
      DROP CONSTRAINT financial_audit_log_operation_type_check;
    -- Recompose the live list verbatim (read 2026-06-30, includes the
    -- 'invoice_unposted' added by 20260625130000) + the new value.
    ALTER TABLE public.financial_audit_log
      ADD CONSTRAINT financial_audit_log_operation_type_check CHECK (operation_type = ANY (ARRAY[
        'invoice_created','invoice_posted','invoice_unposted','invoice_voided','invoice_cancelled',
        'invoice_updated','invoice_deleted','invoice_marked_overdue','payment_recorded','payment_allocation',
        'payment_voided','payment_allocated','split_modified','split_invoices_generated','prepay_created',
        'prepay_applied','prepay_credit_created','prepay_batch_applied','prepay_edited','prepay_deleted',
        'prepay_reconciliation','batch_prepay_apply','write_off_recorded','write_off_reversed','write_off_applied',
        'finance_charge','finance_charge_generated','finance_charge_voided','credit_memo_created','credit_memo_applied',
        'credit_memo_unapplied','return_created','return_approved','return_received','return_credit_issued',
        'order_created','order_updated','order_voided','order_cancelled','order_restored','delivery_created',
        'delivery_updated','delivery_cancelled','delivery_voided','delivery_restored','quote_converted',
        'blend_ticket_linked','blend_ticket_unlinked','commission_payment_created','commission_payment_posted',
        'commission_payment_voided','batch_post','batch_void','batch_payment','period_reopened','quote_status_reverted',
        'blend_ticket_approval_reversed','cycle_count_completed','vendor_bill_created','vendor_bill_voided',
        'vendor_bill_updated','vendor_payment_recorded','vendor_payment_voided',
        'rup_sales_voided'   -- PARKED-006: new entry, additive only.
      ]));
  END IF;
END $$;

-- ── 3. unpost_invoice — also void its RUP rows ──────────────────────────────
-- Verbatim live body (read 2026-06-30) + ONE new block that marks RUP rows
-- voided. Placed AFTER the period guard + status flip, so the existing
-- preconditions still fire identically; the new write follows the same audit
-- discipline as the existing 'invoice_unposted' row.
CREATE OR REPLACE FUNCTION public.unpost_invoice(
  p_invoice_id uuid,
  p_performed_by uuid,
  p_idempotency_key text DEFAULT NULL::text
)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_inv RECORD;
  v_actor_role text;
  v_existing jsonb;
  v_result jsonb;
  v_alloc_count int := 0;
  v_prepay_count int := 0;
  v_rup_voided int := 0;
BEGIN
  SELECT role INTO v_actor_role FROM profiles
    WHERE id = auth.uid() AND is_active = true AND role IN ('admin','sales_rep');
  IF v_actor_role IS NULL THEN
    RAISE EXCEPTION 'Not authorized: requires admin,sales_rep role';
  END IF;
  IF p_performed_by IS DISTINCT FROM auth.uid() THEN
    RAISE EXCEPTION 'ACTOR_MISMATCH: p_performed_by must match the authenticated user';
  END IF;
  IF p_idempotency_key IS NOT NULL THEN
    v_existing := check_idempotency(p_idempotency_key, 'unpost_invoice');
    IF v_existing IS NOT NULL THEN RETURN v_existing; END IF;
  END IF;

  SELECT * INTO v_inv FROM invoices WHERE id = p_invoice_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Invoice not found: %', p_invoice_id; END IF;
  IF v_inv.status NOT IN ('posted', 'overdue') THEN
    IF v_inv.status IN ('draft', 'unposted') THEN
      RAISE EXCEPTION 'Invoice % is not posted (status: %); there is nothing to unpost', v_inv.invoice_number, v_inv.status;
    ELSE
      RAISE EXCEPTION 'Cannot unpost a % invoice (%). Only a posted, unpaid invoice can be returned to the Unposted list.', v_inv.status, v_inv.invoice_number;
    END IF;
  END IF;

  SELECT count(*) INTO v_alloc_count FROM invoice_line_allocations WHERE invoice_id = p_invoice_id;
  SELECT count(*) INTO v_prepay_count FROM prepay_applications     WHERE invoice_id = p_invoice_id;
  IF v_alloc_count > 0
     OR v_prepay_count > 0
     OR COALESCE(v_inv.paid_amount_cents, 0)    <> 0
     OR COALESCE(v_inv.prepay_applied_cents, 0) <> 0
     OR COALESCE(v_inv.write_off_cents, 0)      <> 0
  THEN
    RAISE EXCEPTION 'Cannot unpost invoice % — it has payments, prepay, or write-offs applied. Unallocate those first (or void the invoice instead).', v_inv.invoice_number;
  END IF;

  PERFORM check_period_open(v_inv.invoice_date);

  PERFORM set_config('app.admin_override', 'true', true);
  UPDATE invoices SET
    status      = 'unposted',
    posted_by   = NULL,
    posted_at   = NULL,
    updated_at  = now()
  WHERE id = p_invoice_id;
  PERFORM set_config('app.admin_override', 'false', true);

  -- PARKED-006: void active RUP rows for this invoice. Append-only-with-marker:
  -- mark voided_at + actor + reason, never delete. Idempotent (only touches
  -- rows where voided_at IS NULL — a replay or repeated unpost is a no-op).
  UPDATE rup_sales_records SET
    voided_at  = now(),
    voided_by  = auth.uid(),
    void_reason = 'Invoice ' || v_inv.invoice_number || ' unposted'
  WHERE invoice_id = p_invoice_id
    AND voided_at IS NULL;
  GET DIAGNOSTICS v_rup_voided = ROW_COUNT;

  INSERT INTO financial_audit_log (
    operation_type, entity_type, entity_id, actor_user_id, actor_role,
    old_values, new_values, total_impact_cents, description
  ) VALUES (
    'invoice_unposted', 'invoice', p_invoice_id, auth.uid(), v_actor_role,
    jsonb_build_object('status', v_inv.status, 'posted_at', v_inv.posted_at),
    jsonb_build_object('status', 'unposted', 'unposted_at', now()::text, 'rup_rows_voided', v_rup_voided),
    -1 * COALESCE(v_inv.total_amount_cents, 0),
    'Unposted ' || v_inv.invoice_number || ' (was ' || v_inv.status || ') — $' || (COALESCE(v_inv.total_amount_cents,0) / 100.0)::numeric(12,2)
      || CASE WHEN v_rup_voided > 0 THEN '; ' || v_rup_voided || ' RUP sale row(s) voided' ELSE '' END
  );

  -- PARKED-006: distinct audit row for the RUP void itself (separable, queryable).
  IF v_rup_voided > 0 THEN
    INSERT INTO financial_audit_log (
      operation_type, entity_type, entity_id, actor_user_id, actor_role,
      new_values, total_impact_cents, description
    ) VALUES (
      'rup_sales_voided', 'invoice', p_invoice_id, auth.uid(), v_actor_role,
      jsonb_build_object('rows_voided', v_rup_voided, 'reason', 'invoice_unposted'),
      0,
      v_rup_voided || ' RUP sale row(s) voided for invoice ' || v_inv.invoice_number || ' on unpost'
    );
  END IF;

  INSERT INTO activity_feed (event_type, description, performed_by, related_entity_type, related_entity_id, customer_id)
  VALUES ('invoice_unposted',
    'Unposted invoice ' || v_inv.invoice_number || ' — returned to the Unposted list',
    COALESCE(p_performed_by, auth.uid()), 'invoice', p_invoice_id, v_inv.customer_id);

  v_result := jsonb_build_object(
    'success', true,
    'invoice_id', p_invoice_id,
    'invoice_number', v_inv.invoice_number,
    'previous_status', v_inv.status,
    'status', 'unposted',
    'rup_rows_voided', v_rup_voided   -- PARKED-006: surface to caller
  );

  IF p_idempotency_key IS NOT NULL THEN
    PERFORM save_idempotency(p_idempotency_key, 'unpost_invoice', v_result);
  END IF;

  RETURN v_result;
END;
$function$;

-- ── 4. generate_rup_sales_records — dedup respects voided_at ───────────────
-- The live body's dedup is `NOT EXISTS (… WHERE invoice_id = … AND product_id = …)`.
-- After PARKED-006, a stale voided row would prevent a legitimate re-post from
-- generating a fresh active row. Tighten the dedup to ignore voided rows.
CREATE OR REPLACE FUNCTION public.generate_rup_sales_records(p_invoice_id uuid, p_idempotency_key text DEFAULT NULL::text)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_count integer := 0;
  v_invoice record;
  v_item record;
  v_license record;
  v_compliance_status text;
  v_compliance_notes text;
  v_season integer;
  v_existing jsonb;
  v_result jsonb;
BEGIN
  IF p_idempotency_key IS NOT NULL THEN
    v_existing := check_idempotency(p_idempotency_key, 'generate_rup_sales_records');
    IF v_existing IS NOT NULL THEN
      RETURN (v_existing->>'count')::integer;
    END IF;
  END IF;

  SELECT i.id, i.order_id, o.customer_id, c.farm_name, i.created_at
  INTO v_invoice
  FROM invoices i
  JOIN orders o ON o.id = i.order_id
  JOIN customers c ON c.id = o.customer_id
  WHERE i.id = p_invoice_id;

  IF v_invoice IS NULL THEN RETURN 0; END IF;

  v_season := CASE
    WHEN EXTRACT(MONTH FROM v_invoice.created_at) >= 10
    THEN EXTRACT(YEAR FROM v_invoice.created_at)::integer + 1
    ELSE EXTRACT(YEAR FROM v_invoice.created_at)::integer
  END;

  FOR v_item IN
    SELECT ii.id, ii.product_id, p.product_name, ii.quantity, ii.unit_size,
           ii.unit_price_cents, ii.extended_cents,
           p.epa_registration, p.signal_word
    FROM invoice_items ii
    JOIN products p ON p.id = ii.product_id
    WHERE ii.invoice_id = p_invoice_id
      AND p.is_rup = true
  LOOP
    SELECT al.license_number, al.license_type, al.expiry_date
    INTO v_license
    FROM applicator_licenses al
    WHERE al.customer_id = v_invoice.customer_id
      AND al.is_active = true
    ORDER BY al.expiry_date DESC NULLS LAST
    LIMIT 1;

    IF v_license IS NULL OR v_license.license_number IS NULL THEN
      v_compliance_status := 'non_compliant';
      v_compliance_notes := 'No applicator license on file for this customer';
    ELSIF v_license.expiry_date IS NOT NULL AND v_license.expiry_date < CURRENT_DATE THEN
      v_compliance_status := 'warning';
      v_compliance_notes := 'Applicator license expired on ' || v_license.expiry_date::text;
    ELSE
      v_compliance_status := 'compliant';
      v_compliance_notes := NULL;
    END IF;

    -- PARKED-006: dedup ignores voided rows so a legitimate re-post can record
    -- a fresh active sale even when a prior voided row exists.
    IF NOT EXISTS (
      SELECT 1 FROM rup_sales_records
      WHERE invoice_id = p_invoice_id
        AND product_id = v_item.product_id
        AND voided_at IS NULL
    ) THEN
      INSERT INTO rup_sales_records (
        invoice_id, order_id, customer_id, product_id,
        sale_date, product_name, epa_registration, quantity, unit,
        unit_price_cents, total_cents,
        buyer_name, buyer_certification_number,
        buyer_certification_type, buyer_certification_expiry,
        signal_word, compliance_status, compliance_notes,
        season, created_by
      ) VALUES (
        p_invoice_id, v_invoice.order_id, v_invoice.customer_id, v_item.product_id,
        CURRENT_DATE, v_item.product_name, v_item.epa_registration, v_item.quantity, v_item.unit_size,
        v_item.unit_price_cents, v_item.extended_cents,
        v_invoice.farm_name,
        v_license.license_number,
        v_license.license_type,
        v_license.expiry_date,
        v_item.signal_word, v_compliance_status, v_compliance_notes,
        v_season, auth.uid()
      );
      v_count := v_count + 1;
    END IF;
  END LOOP;

  v_result := jsonb_build_object('count', v_count);

  IF p_idempotency_key IS NOT NULL THEN
    PERFORM save_idempotency(p_idempotency_key, 'generate_rup_sales_records', v_result);
  END IF;

  RETURN v_count;
END;
$function$;

-- ── 5. get_rup_sales_register — exclude voided by default ─────────────────────
-- New parameter `p_include_voided boolean DEFAULT false` to opt-in if needed.
-- Existing callers (no arg) get the new default — "active sales only".
DROP FUNCTION IF EXISTS public.get_rup_sales_register(date, date, uuid, uuid, text);

CREATE OR REPLACE FUNCTION public.get_rup_sales_register(
  p_start_date date DEFAULT NULL,
  p_end_date date DEFAULT NULL,
  p_product_id uuid DEFAULT NULL,
  p_customer_id uuid DEFAULT NULL,
  p_compliance_status text DEFAULT NULL,
  p_include_voided boolean DEFAULT false
)
 RETURNS TABLE(
   id uuid, sale_date date, invoice_id uuid, customer_id uuid,
   buyer_name text, product_name text, epa_registration text,
   quantity numeric, unit text, unit_price_cents bigint, total_cents bigint,
   buyer_certification_number text, buyer_certification_type text,
   buyer_certification_expiry date, signal_word text,
   compliance_status text, compliance_notes text, season integer,
   voided_at timestamptz, voided_by uuid, void_reason text
 )
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
BEGIN
  RETURN QUERY
  SELECT
    r.id, r.sale_date, r.invoice_id, r.customer_id,
    r.buyer_name, r.product_name, r.epa_registration,
    r.quantity, r.unit, r.unit_price_cents, r.total_cents,
    r.buyer_certification_number, r.buyer_certification_type,
    r.buyer_certification_expiry, r.signal_word,
    r.compliance_status, r.compliance_notes, r.season,
    r.voided_at, r.voided_by, r.void_reason
  FROM rup_sales_records r
  WHERE (p_start_date IS NULL OR r.sale_date >= p_start_date)
    AND (p_end_date   IS NULL OR r.sale_date <= p_end_date)
    AND (p_product_id IS NULL OR r.product_id = p_product_id)
    AND (p_customer_id IS NULL OR r.customer_id = p_customer_id)
    AND (p_compliance_status IS NULL OR r.compliance_status = p_compliance_status)
    AND (p_include_voided OR r.voided_at IS NULL)
  ORDER BY r.sale_date DESC, r.buyer_name;
END;
$function$;

-- PARKED-006 r2 (Codex catch): DROP FUNCTION drops grants. The new 6-arg
-- get_rup_sales_register defaulted to PUBLIC EXECUTE, which would have
-- reopened this SECURITY DEFINER compliance report to anon — exactly the
-- exposure this migration is supposed to prevent. Restate grants explicitly.
REVOKE ALL ON FUNCTION public.get_rup_sales_register(date, date, uuid, uuid, text, boolean) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.get_rup_sales_register(date, date, uuid, uuid, text, boolean) FROM anon;
GRANT EXECUTE ON FUNCTION public.get_rup_sales_register(date, date, uuid, uuid, text, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_rup_sales_register(date, date, uuid, uuid, text, boolean) TO service_role;

-- generate_rup_sales_records was CREATE OR REPLACE'd above (which preserves
-- existing grants), but restate defense-in-depth to keep the posture explicit.
REVOKE ALL ON FUNCTION public.generate_rup_sales_records(uuid, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.generate_rup_sales_records(uuid, text) FROM anon;
GRANT EXECUTE ON FUNCTION public.generate_rup_sales_records(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.generate_rup_sales_records(uuid, text) TO service_role;

-- NOTE FOR MASON (post-apply, not part of this migration):
--   1. Run `npm run generate-types` (or the Supabase CLI equivalent) to
--      regenerate src/types/index.ts — the new voided_at / voided_by /
--      void_reason columns on rup_sales_records need to be reflected there,
--      and get_rup_sales_register's return type + new p_include_voided arg
--      need the typed shape refreshed.
--   2. Smoke the full round-trip on a real RUP product before declaring done:
--      (a) create + post an invoice with a RUP product → RUP row written,
--          register shows it.
--      (b) unpost the invoice → the RUP row now has voided_at IS NOT NULL,
--          register hides it by default, p_include_voided=true reveals it.
--      (c) re-post the invoice → fresh active RUP row alongside the voided
--          one (dedup is voided-aware), register shows the active one only.

-- SELF-VERIFICATION
DO $$
DECLARE v_cols int; v_unpost_src text; v_gen_src text; v_reg_src text;
BEGIN
  SELECT count(*) INTO v_cols FROM information_schema.columns
    WHERE table_schema='public' AND table_name='rup_sales_records'
      AND column_name IN ('voided_at', 'voided_by', 'void_reason');
  IF v_cols <> 3 THEN RAISE EXCEPTION 'PARKED-006: void columns not all present (found %)', v_cols; END IF;

  SELECT prosrc INTO v_unpost_src FROM pg_proc WHERE proname='unpost_invoice' AND pronamespace='public'::regnamespace;
  IF position('PARKED-006' in v_unpost_src) = 0 THEN RAISE EXCEPTION 'PARKED-006: marker missing from unpost_invoice'; END IF;
  IF position('UPDATE rup_sales_records' in v_unpost_src) = 0 THEN RAISE EXCEPTION 'PARKED-006: unpost_invoice missing RUP void block'; END IF;
  IF position('rup_sales_voided' in v_unpost_src) = 0 THEN RAISE EXCEPTION 'PARKED-006: unpost_invoice missing rup_sales_voided audit row'; END IF;

  SELECT prosrc INTO v_gen_src FROM pg_proc WHERE proname='generate_rup_sales_records' AND pronamespace='public'::regnamespace;
  IF position('voided_at IS NULL' in v_gen_src) = 0 THEN RAISE EXCEPTION 'PARKED-006: generate_rup_sales_records dedup not voided-aware'; END IF;

  SELECT prosrc INTO v_reg_src FROM pg_proc WHERE proname='get_rup_sales_register' AND pronamespace='public'::regnamespace;
  IF position('p_include_voided' in v_reg_src) = 0 THEN RAISE EXCEPTION 'PARKED-006: get_rup_sales_register missing p_include_voided'; END IF;

  -- CHECK constraint must include rup_sales_voided
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conrelid='public.financial_audit_log'::regclass
       AND conname='financial_audit_log_operation_type_check'
       AND position('rup_sales_voided' in pg_get_constraintdef(oid)) > 0
  ) THEN
    RAISE EXCEPTION 'PARKED-006: financial_audit_log CHECK missing rup_sales_voided';
  END IF;

  -- PARKED-006 r2: confirm anon and PUBLIC do NOT have EXECUTE on the SECDEF
  -- report function. A DROP FUNCTION reset its grants; an unset migration
  -- would silently reopen the report.
  IF EXISTS (
    SELECT 1
      FROM pg_proc p
      JOIN pg_namespace n ON n.oid = p.pronamespace
     WHERE n.nspname = 'public'
       AND p.proname = 'get_rup_sales_register'
       AND has_function_privilege('anon', p.oid, 'EXECUTE')
  ) THEN
    RAISE EXCEPTION 'PARKED-006: anon has EXECUTE on get_rup_sales_register — privilege regression';
  END IF;
END $$;
